//This file will contain all of the bible data that doesn't need to be pulled from an API or database.
import { BookAndChapters, BibleVersions } from "@/lib/definitions";

export const EnglishBibleVersions: BibleVersions[] = [
	{ value: "en-asv", title: "American Standard Version of the Holy Bible" },
	{ value: "en-US-asvbt", title: "American Standard Version Byzantine Text with Apocrypha" },
	{ value: "en-bsb", title: "Berean Study Bible" },
	{ value: "en-engbrent", title: "Brenton English Septuagint" },
	{ value: "en-US-lxxup", title: "Brenton English Septuagint (Updated Spelling and Formatting)" },
	{ value: "en-dra", title: "Douay-Rheims American 1899" },
	{ value: "en-US-emtv", title: "English Majority Text Version" },
	{ value: "en-fbv", title: "Free Bible Version" },
	{ value: "en-gnv", title: "Geneva Bible" },
	{ value: "en-ojps", title: "JPS TaNaKH 1917" },
	{ value: "en-kjv", title: "King James Version of the Holy Bible" },
	{ value: "en-lsv", title: "Literal Standard Version" },
	{ value: "en-rv", title: "Revised Version" },
	{ value: "en-oke", title: "Targum Onkelos Etheridge" },
	{ value: "en-tcent", title: "Text-Critical English New Testament" },
	{ value: "en-t4t", title: "The Holy Bible: A Translation for Translators" },
	{ value: "en-US-f35", title: "The English New Testament According to Family 35" },
	{ value: "en-US-kjvcpb", title: "The Cambridge Paragraph Bible of the Authorized English Version" },
	{ value: "en-web", title: "World English Bible" },
	{ value: "en-webbe", title: "World English Bible British Edition" },
	{ value: "en-webus", title: "World English Bible, American English Edition, without Strong's numbers" },
	{ value: "en-wmb", title: "World Messianic Bible" },
	{ value: "en-wmbbe", title: "World Messianic Bible British Edition" },
];


export const oldTestamentBooks: BookAndChapters[] = [
	{ book: "Genesis", chapters: 50 },
	{ book: "Exodus", chapters: 40 },
	{ book: "Leviticus", chapters: 27 },
	{ book: "Numbers", chapters: 36 },
	{ book: "Deuteronomy", chapters: 34 },
	{ book: "Joshua", chapters: 24 },
	{ book: "Judges", chapters: 21 },
	{ book: "Ruth", chapters: 4 },
	{ book: "1 Samuel", chapters: 31 },
	{ book: "2 Samuel", chapters: 24 },
	{ book: "1 Kings", chapters: 22 },
	{ book: "2 Kings", chapters: 25 },
	{ book: "1 Chronicles", chapters: 29 },
	{ book: "2 Chronicles", chapters: 36 },
	{ book: "Ezra", chapters: 10 },
	{ book: "Nehemiah", chapters: 13 },
	{ book: "Esther", chapters: 10 },
	{ book: "Job", chapters: 42 },
	{ book: "Psalms", chapters: 150 },
	{ book: "Proverbs", chapters: 31 },
	{ book: "Ecclesiastes", chapters: 12 },
	{ book: "Song of Solomon", chapters: 8 },
	{ book: "Isaiah", chapters: 66 },
	{ book: "Jeremiah", chapters: 52 },
	{ book: "Lamentations", chapters: 5 },
	{ book: "Ezekiel", chapters: 48 },
	{ book: "Daniel", chapters: 12 },
	{ book: "Hosea", chapters: 14 },
	{ book: "Joel", chapters: 3 },
	{ book: "Amos", chapters: 9 },
	{ book: "Obadiah", chapters: 1 },
	{ book: "Jonah", chapters: 4 },
	{ book: "Micah", chapters: 7 },
	{ book: "Nahum", chapters: 3 },
	{ book: "Habakkuk", chapters: 3 },
	{ book: "Zephaniah", chapters: 3 },
	{ book: "Haggai", chapters: 2 },
	{ book: "Zechariah", chapters: 14 },
	{ book: "Malachi", chapters: 4 },
];

export const newTestamentBooks: BookAndChapters[] = [
	{ book: "Matthew", chapters: 28 },
	{ book: "Mark", chapters: 16 },
	{ book: "Luke", chapters: 24 },
	{ book: "John", chapters: 21 },
	{ book: "Acts", chapters: 28 },
	{ book: "Romans", chapters: 16 },
	{ book: "1 Corinthians", chapters: 16 },
	{ book: "2 Corinthians", chapters: 13 },
	{ book: "Galatians", chapters: 6 },
	{ book: "Ephesians", chapters: 6 },
	{ book: "Philippians", chapters: 4 },
	{ book: "Colossians", chapters: 4 },
	{ book: "1 Thessalonians", chapters: 5 },
	{ book: "2 Thessalonians", chapters: 3 },
	{ book: "1 Timothy", chapters: 6 },
	{ book: "2 Timothy", chapters: 4 },
	{ book: "Titus", chapters: 3 },
	{ book: "Philemon", chapters: 1 },
	{ book: "Hebrews", chapters: 13 },
	{ book: "James", chapters: 5 },
	{ book: "1 Peter", chapters: 5 },
	{ book: "2 Peter", chapters: 3 },
	{ book: "1 John", chapters: 5 },
	{ book: "2 John", chapters: 1 },
	{ book: "3 John", chapters: 1 },
	{ book: "Jude", chapters: 1 },
	{ book: "Revelation", chapters: 22 },
];
